services:
  - type: web
    name: examflow-backend
    env: python
    rootDir: examflow-backend
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate"
    startCommand: "gunicorn examflow_backend.wsgi:application --bind 0.0.0.0:$PORT"
    envVars:
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        value: "django-insecure-examflow-local-dev-key-2026"
      - key: DATABASE_URL
        value: "postgresql://postgres:EEmSUabQjsQKHiFKPiDSLZeQYdVADoSf@switchyard.proxy.rlwy.net:52124/railway"
      - key: RENDER_EXTERNAL_HOSTNAME
        value: "examflow-h6hv.onrender.com"
